version: '3'

services:
  apache-php:
      build: ./apache-php
      container_name: apache-php
      expose:
        - 80
      volumes:
        - /var/log/apache2:/var/log/apache2
        - ./index.php:/var/www/html/index.php
      restart: always

  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - '8888:8888'
      volumes:
        - /var/log/nginx:/var/log/nginx
        - ./default.conf:/etc/nginx/conf.d/default.conf
      restart: always
      links:
        - apache-php

